import os
from api_config import GOOGLE_API_KEY
from google import genai
from datetime import datetime

class ComparisonAgent:
    def __init__(self):
        self.client = genai.Client(api_key=GOOGLE_API_KEY)
        self.model_id = 'gemini-2.5-flash'
    
    def compare_companies(self, companies_data: list) -> dict:
        '''Compare multiple companies and generate comparative analysis'''
        print(f'\n?? Comparing {len(companies_data)} companies...')
        
        company_names = [data['company_name'] for data in companies_data]
        
        # Prepare comparison data
        comparison_prompt = f'''
You are a business analyst comparing multiple companies. Based on the comprehensive data provided for each company, create a detailed comparative analysis.

COMPANIES BEING COMPARED: {', '.join(company_names)}

'''
        
        # Add each company's data
        for i, company_data in enumerate(companies_data, 1):
            company_name = company_data['company_name']
            comparison_prompt += f'''
{'=' * 80}
COMPANY {i}: {company_name}
{'=' * 80}

Company Overview:
{company_data.get('company_research', {}).get('summary', 'N/A')}

Competitors:
{company_data.get('competitors_research', {}).get('identified_competitors', 'N/A')}

Competitive Analysis:
{company_data.get('competitive_analysis', {}).get('competitive_analysis', 'N/A')}

SWOT Analysis:
{company_data.get('swot_analysis', {}).get('swot_analysis', 'N/A')}

Pricing:
{company_data.get('pricing_analysis', {}).get('analysis', 'N/A')}

'''
        
        comparison_prompt += f'''
Based on ALL the above data, create a comprehensive multi-company comparison with these sections:

## Comparative Analysis: {' vs '.join(company_names)}

### 1. Market Position Comparison
Compare how each company is positioned in the market:
- Market share and dominance
- Target audience and segments
- Geographic presence
- Brand strength

### 2. Product & Service Comparison
Compare offerings:
- Core products/services
- Feature differentiation
- Innovation and unique value propositions
- Product maturity

### 3. Competitive Advantages
For each company, identify:
- Unique strengths
- What makes them stand out
- Areas where they lead

### 4. Competitive Weaknesses
For each company, identify:
- Vulnerabilities
- Areas where competitors have advantage
- Market gaps they haven't filled

### 5. Pricing Strategy Comparison
Compare pricing approaches:
- Pricing models
- Value positioning (premium vs budget)
- Pricing flexibility

### 6. SWOT Comparison Matrix
Create a side-by-side comparison of:
- Key strengths of each
- Main weaknesses of each
- Biggest opportunities
- Common threats

### 7. Head-to-Head Analysis
Direct comparison addressing:
- Who is winning in different segments?
- Feature parity analysis
- Customer preference indicators

### 8. Strategic Positioning
- Where each company fits in the competitive landscape
- Future trajectory predictions
- Strategic moves to watch

### 9. Winner Analysis
For different criteria, identify the leader:
- Best for enterprise customers
- Best for startups/SMBs
- Best pricing value
- Best innovation
- Best market position

### 10. Final Verdict
Overall comparison summary and insights.

Be specific, data-driven, and objective. Use the actual information provided for each company.
'''
        
        response = self.client.models.generate_content(
            model=self.model_id,
            contents=comparison_prompt
        )
        
        comparison = {
            'comparison_analysis': response.text,
            'companies_compared': company_names,
            'comparison_date': datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        }
        
        print(f'? Multi-company comparison complete')
        
        return comparison
    
    def generate_comparison_report(self, comparison_data: dict) -> str:
        '''Generate markdown report for comparison'''
        company_names = comparison_data['companies_compared']
        
        report = f'''# Multi-Company Competitive Comparison
*Comparing: {', '.join(company_names)}*
*Generated on {datetime.now().strftime('%B %d, %Y at %H:%M')}*

---

{comparison_data['comparison_analysis']}

---

## Report Metadata
- **Companies Analyzed**: {len(company_names)}
- **Companies**: {', '.join(company_names)}
- **Analysis Date**: {comparison_data['comparison_date']}
- **Report Type**: Multi-Company Comparative Analysis

---

*Generated by Competitive Analysis Agent*
'''
        
        return report
    
    def save_comparison_report(self, report: str, company_names: list) -> str:
        '''Save comparison report to file'''
        companies_str = '_vs_'.join([name.replace(' ', '_') for name in company_names])
        filename = f'comparison_{companies_str}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md'
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(report)
        
        print(f'\n?? Comparison report saved to: {filename}')
        
        return filename
